# ==================================================
# Goal
# 目标位置
# ==================================================

geometry_msgs/PoseStamped goal_pose


---

# ==================================================
# Result
# 最终结果
# ==================================================

bool success

string message

float32 total_time


---

# ==================================================
# Feedback
# 实时反馈
# ==================================================

string state

float32 distance_to_goal

float32 progress