uav_mapping:
  ros__parameters:

    # ==========================
    # 无人机自身点云过滤
    # ==========================
    self_filter_enable: true
    # 相对于 base_link / Body FLU
    self_filter_min:
      [-0.35, -0.35, -0.35]
    self_filter_max:
      [ 0.35,  0.35,  0.35]

    lidar_time_offset: 0.0

    # Gazebo仿真统一使用sim time
    use_sim_time: true

    frame_id: "map"

    # 保存最近3秒PX4位姿
    pose_buffer_duration: 3.0

    # 等待位姿对齐的LiDAR帧最多缓存10帧
    max_cloud_queue_size: 10

    # ==========================
    # ROS topics
    # ==========================

    odom_topic: "/fmu/out/vehicle_odometry"

    # 改成你现在RViz已经验证过的实际topic
    cloud_topic: "/lidar_3d/points"


    # ==========================
    # Voxel Map
    # ==========================

    resolution: 0.20

    map_min:
      [-15.0, -15.0, -1.0]

    map_max:
      [15.0, 15.0, 8.0]


    # 无人机安全半径
    inflation_radius: 0.45


    # ==========================
    # LiDAR
    # ==========================

    min_range: 0.30
    max_range: 20.0


    # 1 = 所有点
    # 2 = 每两个点取一个
    point_stride: 1


    # ==========================
    # LiDAR -> Body FLU 外参
    # ==========================

    lidar_xyz:
      [0.12, 0.0, 0.315]

    # roll pitch yaw，单位rad
    lidar_rpy:
      [0.0, 0.0, 0.0]


    # ==========================
    # 发布频率
    # ==========================

    publish_rate: 2.0